
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('workoutList').del()
    .then(function () {
      // Inserts seed entries
      return knex('workoutList').insert([
        {bodyPart: 1, workout: 'Barbell Bench Press', desc: "<p>Lay down on a bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.</p>\n<p>If you train with a high weight it is advisable to have a <em>spotter</em> that can help you up if you can't lift the weight on your own.</p>\n<p>With the width of the grip you can also control which part of the chest is trained more:</p>\n<ul>\n<li>wide grip: outer chest muscles</li>\n<li>narrow grip: inner chest muscles and triceps</li>\n</ul>", imgURL: 'https://cdn-ami-drupal.heartyhosting.com/sites/muscleandfitness.com/files/media/Bench-Press-Main-800x800.jpg'},
        {bodyPart: 1, workout: 'Cable Crossover', desc: "<p>Begin with cables at about shoulder height, one in each hand. Take a step forward so that one foot is in front of the other, for stability, and so that there is tension on the cables. Bring hands together in front of you. Try to make your hands overlap (so that the cables cross) a few inches.</p>", imgURL: 'https://images-na.ssl-images-amazon.com/images/I/61e3ZHHT5JS._SX425_.jpg'},
        {bodyPart: 1, workout: 'Dumbbell Bench Press', desc: "<p>The movement is very similar to benchpressing with a barbell, however, the weight is brought down to the chest at a lower point.</p>\n<p>Hold two dumbbells and lay down on a bench. Hold the weights next to the chest, at the height of your nipples and press them up till the arms are stretched. Let the weight slowly and controlled down.</p>", imgURL: 'http://s3.amazonaws.com/prod.skimble/assets/965616/image_iphone.jpg'},
        {bodyPart: 1, workout: 'Decline Barbell Bench Press', desc: "<p>Lay down on a decline bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.</p>", imgURL: 'https://i.pinimg.com/originals/ef/d9/9e/efd99e193cccaa498dcca508e5c7bfa9.png'},
        {bodyPart: 1, workout: 'Dumbbell Flyes', desc: "<p>Take two dumbbells and lay on a bench, make sure the feet are firmly on the ground and your back is not arched, but has good contact with the bench. The arms are stretched in front of you, about shoulder wide. Bend now the arms a bit and let them down with a half-circle movement to the side. Without changing the angle of the elbow bring them in a fluid movement back up.</p>", imgURL: 'https://i.pinimg.com/originals/99/7e/cb/997ecb5d93c366028b484af706dd87f3.jpg'},
        {bodyPart: 2, workout: 'Bent Over Barbell Row', desc: "<ol>\n<li>Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.</li>\n<li>Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.</li>\n<li>Then inhale and slowly lower the barbell back to the starting position.</li>\n<li>Repeat for the recommended amount of repetitions.</li>\n</ol>", imgURL: 'https://julielohre.com/wp-content/uploads/2017/11/Bent-Over-Barbell-Row.jpg'},
        {bodyPart: 2, workout: 'Close-grip Lat Pull Down', desc: "<p>Grip the pull-down bar with your hands closer than shoulder width apart, with your palms facing away from you. Lean back slightly. Pull the bar down towards your chest, keeping your elbows close to your sides as you come down. Pull your shoulders back at the end of the motion.</p>", imgURL: 'https://i.pinimg.com/originals/c2/c1/46/c2c146dc74c71d706aa763ea841153f0.jpg'},
        {bodyPart: 3, workout: 'Barbell Lunges', desc: "<p>Put barbell on the back of your shoulders. Stand upright, then take the first step forward. Step should bring you forward so that your supporting legs knee can touch the floor. Then stand back up and repeat with the other leg.</p>\n<p>Remember to keep good posture.</p>", imgURL: 'http://fitnessstars.weebly.com/uploads/5/8/8/7/58879495/4201500_orig.png'},
        {bodyPart: 3, workout: 'Dumbbell Goblet Squat', desc: "<p>Grasp dumbbell with both hands at the sides of the upper plates. Hold dumbbell in front of chest, close to torso. Place feet about shoulderwide apart, keep knees slightly bent.</p>\n<p>Squat down until thighs are parallel to floor. Keep back straight, bend and move hips backward to keep knees above feet. Return, keep knees slightly flexed. Repeat.</p>\n<p>Keep bodyweight on heels and look ahead or slightly above to keep back straight.</p>", imgURL: 'http://assets.menshealth.co.uk/main/thumbs/28351/goblet-squat-SeI9iu-promo__square.jpg'},
        {bodyPart: 4, workout: 'Calf Press Using Leg Press Machine', desc: "<p>Put  the balls of your feet on an extended leg press pad.  Use your calves to press the weight by flexing your feet/toes into a pointed position, and releasing back into a relaxed position.</p>\n<p>This exercise builds mass and strength in the Gastrocnemius and Soleus muscles as well, if not better, than any calf exercise.</p>", imgURL: 'https://www.fitdir.com/media/catalog/product/cache/30/thumbnail/522x/9df78eab33525d08d6e5fb8d27136e95/c/a/calf_up.jpg'},
        {bodyPart: 4, workout: 'Sitting Calf Raises', desc: "<p>Sit on a bench for calf raises and check that the feet are half free and that you can completely stretch the calf muscles down. Pull your calves up, going as far (up) as you can. Make at the highest point a short pause of 1 or 2 seconds and go down.</p>", imgURL: 'https://images-na.ssl-images-amazon.com/images/I/41uMBDYmP%2BL._SX425_.jpg'},
        {bodyPart: 5, workout: 'Biceps Curls With Barbell', desc: "<p>Hold the Barbell shoulder-wide, the back is straight, the shoulders slightly back, the arms are streched. Bend the arms, bringing the weight up, with a fast movement. Without pausing, let down the bar with a slow and controlled movement.</p>\n<p>Don't allow your body to swing during the exercise, all work is done by the biceps, which are the only mucles that should move (pay attention to the elbows).</p>", imgURL: 'https://s3.amazonaws.com/images.myfit.ca/cache/images/standinge-zcurlbar_002.gif'},
        {bodyPart: 5, workout: 'Biceps Curls With Dumbbell', desc: "<p>Hold two barbells, the arms are streched, the hands are on your side, the palms face inwards. Bend the arms and bring the weight with a fast movement up. At the same time, rotate your arms by 90 degrees at the very beginning of the movement. At the highest point, rotate a little the weights further outwards. Without a pause, bring them down, slowly.</p>\n<p>Don't allow your body to swing during the exercise, all work is done by the biceps, which are the only mucles that should move (pay attention to the elbows).</p>", imgURL: 'https://www.mensjournal.com/wp-content/uploads/mf/hammer_cheat_curl_main.jpg'},
        {bodyPart: 6, workout: 'Facepull', desc: "<p>Attach a rope to a pulley station set at about chest level.</p>\n<p>Step back so you're supporting the weight with arms completely outstretched and assume a staggered (one foot forward) stance. Bend the knees slightly for a stable base.</p>\n<p>Retract the scapulae (squeeze your partner's finger with your shoulder blades) and pull the center of the rope slightly up towards the face. A good cue is to think about pulling the ends of the rope apart, not just pulling back.</p>\n<p>As you near your face, externally rotate so your knuckles are facing the ceiling.</p>\n<p>Hold for one second at the top position and slowly lower.</p>", imgURL: 'https://cdn-xi3mbccdkztvoept8hl.netdna-ssl.com/wp-content/uploads/watermarked/Face_pull_F_WorkoutLabs.png'},
        {bodyPart: 6, workout: 'Front Raises', desc: "<p>To execute the exercise, the lifter stands with their feet shoulder width apart and weights or resistance handles held by their side with a pronated (overhand) grip.</p>\n<p>The movement is to bring the arms up in front of the body to eye level and with only a slight bend in the elbow. This isolates the anterior deltoid muscle (front of the shoulder) and uses the anterior deltoid to lift the weight.</p>\n<p>When lifting it is important to keep the body still so the anterior deltoid is fully utilised; if the weight cannot be lifted by standing still then it is too heavy and a lower weight is needed. It is important to keep a slight bend in the elbow when lifting as keeping the elbow locked will add stress to the elbow joint and could cause injury.</p>\n<p>A neutral grip, similar to that used in the hammer curl, can also be used. With this variation the weight is again raised to eye level, but out to a 45 degree angle from the front of the body. This may be beneficial for those with shoulder injuries, particularly those related to the rotator cuff.</p>", imgURL: 'http://s3.amazonaws.com/prod.skimble/assets/1133115/image_iphone.jpg'},
        {bodyPart: 7, workout: 'Barbell Ab Rollout', desc: "<p>Place a barbell on the floor at your feet.</p>\n<p>Bending at the waist, grip the barbell with a shoulder with overhand grip.</p>\n<p>With a slow controlled motion, roll the bar out so that your back is straight.</p>\n<p>Roll back up raising your hips and butt as you return to the starting position.</p>", imgURL: 'http://epphany.com/gallery/ca34eaadf737e911efb52b4bc826846b'},
        {bodyPart: 7, workout: 'Crunches', desc: "<p>Lay down on your back a soft surface, the feet are on the floor. Ask a partner or use some other help (barbell, etc.) to keep them fixed, your hands are behind your head. From this position move your upper body up till your head or elbows touch your knees. Do this movement by rolling up your back.</p>", imgURL: 'https://i.stack.imgur.com/pxchZ.png'}
      ]);
    });
};
